<?xml version="1.0" encoding="UTF-8" ?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:aop="http://www.springframework.org/schema/aop"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
 		http://www.springframework.org/schema/beans/spring-beans.xsd
 		http://www.springframework.org/schema/aop
 		http://www.springframework.org/schema/aop/spring-aop.xsd">

	<bean id="mythrow" class="com.wendao.advice.MyThrowAdvice"></bean>

	<!-- 异常通知，使用AspectJ -->
	<aop:config>
		<aop:aspect ref="mythrow">
			<aop:pointcut 
				expression="execution(* com.wendao.test.*.*(..))" 
				id="mypoint"/>
				
			<aop:after-throwing 
				method="myexception" 
				pointcut-ref="mypoint"
				throwing="e" />
			<!--
				 method: 设置 切点触发异常时，调用的方法。此方法所在的class 在ref中配置		
				 pointcut-ref: 设置切点
				 throwing: 设置异常参数e
			 -->
				
			
			<!-- 具体流程：
				当切点触发异常时，
					调用的是方法是 ref="mythrow"配置的class的 method="myexception"
					
				注意：使用Spring时，在service方法中不用try/catch 而用throw。
					否则spring不知道异常，在处理事务时，不能rollback
			 -->
		</aop:aspect>
	</aop:config>
	
	
	<bean id="demo" class="com.wendao.test.Demo"></bean>
	

</beans>













